source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-logging", path: "../google-cloud-logging"
gem "google-cloud-pubsub-v1", path: "../google-cloud-pubsub-v1"

gem "rake"
